# Generated by Django 3.0.8 on 2020-11-27 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="test",
            field=models.CharField(default="working", max_length=200),
        ),
    ]
